(() => {
const sb=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_KEY);let user=null;
const $=id=>document.getElementById(id);const msg=(t,c='')=>{$('status').textContent=t;$('status').className='status '+c};
const slugify=s=>String(s||'').toLowerCase().trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')||'tulisan';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const defaults={
 home_eyebrow:'02:00 — 02:59',home_micro:'SEBUAH RUANG UNTUK MENULIS',home_title1:'yang kita',home_title2:'bicarakan',home_lead:'Beberapa hal hanya berani kita katakan ketika dunia sudah mulai diam.',home_cta:'masuk ke dalam',home_note:'Mungkin kita belum selesai.',home_note_italic:'Mungkin memang tidak pernah.',home_random:'baca sesuatu secara acak',home_poem_micro:'YANG TERASA, TAPI TAK TERUCAP.',home_poem_heading:'Puisi',home_journal_micro:'CATATAN DARI HARI-HARI BIASA.',home_journal_heading:'Jurnal',home_interlude:'Jika kau sampai di sini,\nmungkin ada bagian dari diriku\nyang sedang kau cari.',home_interlude_author:'— catatan yang tidak selesai',home_archive_title:'Yang pernah\nditulis.',home_archive_desc:'Cari sesuatu di antara malam-malam yang lewat.',home_about_micro:'TENTANG RUANG INI',home_about_title:'Sebuah rumah\nuntuk tulisan.',home_about_p1:'Aku membuat tempat ini untuk hal-hal yang biasanya kita simpan.',home_about_p2:'Tentang orang yang pernah kita tunggu. Tentang rumah yang pernah kita tinggalkan. Tentang percakapan yang berhenti sebelum selesai.',home_about_p3:'Sebagian tulisan lahir pukul dua dini hari. Sebagian lainnya baru berani ditulis ketika pagi datang.',home_about_p4:'Kalau kau menemukan sesuatu di sini yang terasa seperti pernah kau alami, mungkin kita pernah berada di malam yang sama.',home_about_name:'— Bobby Dustiansyah',
 about_eyebrow:'04 — TENTANG',about_title1:'Tempat untuk',about_title2:'hal-hal yang tinggal.',about_intro:'Tidak semua yang kita rasakan harus segera dijelaskan. Beberapa hal cukup ditulis, lalu dibiarkan menemukan pembacanya sendiri.',about_story1_label:'MENGAPA RUANG INI ADA',about_story1_heading:'Karena ada percakapan yang hanya berani kita lakukan ketika malam sudah terlalu larut.',about_story1_p1:'Ada kalimat yang kita simpan terlalu lama. Ada nama yang sengaja tidak disebut. Ada kenangan yang tidak benar-benar pergi, hanya berubah menjadi sesuatu yang kita bawa diam-diam.',about_story1_p2:'Ruang ini dibuat untuk hal-hal semacam itu.',about_story1_p3:'Bukan untuk menjelaskan semuanya. Bukan pula untuk mencari jawaban. Hanya sebuah tempat kecil untuk meletakkan apa yang terlalu penuh jika terus dibawa sendirian.',about_quote:'Mungkin menulis bukan tentang\nmenemukan kata yang tepat,\ntetapi menemukan tempat\nuntuk kata-kata yang tidak pernah sempat kita ucapkan.',about_story2_label:'TENTANG PUKUL DUA DINI HARI',about_story2_heading:'Jam ketika suara dunia mengecil dan suara di kepala menjadi lebih jujur.',about_story2_p1:'Pukul dua dini hari bukan sekadar waktu di tempat ini. Ia adalah suasana.',about_story2_p2:'Ia adalah jeda setelah hari selesai, ketika tidak ada lagi yang perlu kita buktikan kepada siapa-siapa. Ketika kita bisa duduk sendiri dan akhirnya mendengar apa yang selama siang hari kita abaikan.',about_story2_p3:'Di situlah sebagian tulisan di sini lahir.',about_principles_label:'03 — CARA RUANG INI BERTUMBUH',about_principle1_title:'Tidak terburu-buru.',about_principle1_body:'Tulisan tidak harus selalu baru. Beberapa tulisan membutuhkan waktu sebelum siap dibaca orang lain.',about_principle2_title:'Tidak harus menjelaskan.',about_principle2_body:'Sebuah puisi boleh menjadi pertanyaan. Sebuah jurnal boleh berakhir tanpa kesimpulan.',about_principle3_title:'Tetap manusia.',about_principle3_body:'Di balik setiap tulisan ada seseorang yang pernah merasa, kehilangan, menunggu, dan mencoba pulang.',about_signature_p:'Kalau kau menemukan sesuatu di sini\nyang terasa seperti pernah kau alami,',about_signature_h2:'mungkin kita pernah berada\ndi malam yang sama.',about_signature_name:'— Bobby Dustiansyah'
};
const groups=[['BERANDA','home_',Object.keys(defaults).filter(k=>k.startsWith('home_'))],['TENTANG','about_',Object.keys(defaults).filter(k=>k.startsWith('about_'))]];
function label(k){return k.replace(/^(home|about)_/,'').replace(/_/g,' ').replace(/\b\w/g,x=>x.toUpperCase())}
async function init(){const {data,error}=await sb.auth.getUser();if(error||!data.user){location.href='login.html';return}user=data.user;await loadPosts();await loadSite()}
async function loadPosts(){const {data,error}=await sb.from('poems').select('*').order('created_at',{ascending:false});if(error){msg('Gagal memuat tulisan: '+error.message,'error');return}if(!data?.length){$('postList').innerHTML='<p>Belum ada tulisan.</p>';return}$('postList').innerHTML=data.map(x=>`<div class="card"><div><strong>${esc(x.title||'(tanpa judul)')}</strong><div class="meta">${esc(x.type||'puisi')} · ${esc(x.theme||'')} · ${esc(x.status||'')}</div></div><div class="card-actions"><button class="btn" data-edit="${x.id}">Edit</button><button class="btn" data-toggle="${x.id}" data-status="${x.status}">${x.status==='published'?'Jadikan Draft':'Terbitkan'}</button><button class="btn danger" data-delete="${x.id}">Hapus</button></div></div>`).join('');document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editPost(b.dataset.edit));document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>togglePost(b.dataset.toggle,b.dataset.status));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deletePost(b.dataset.delete))}
async function editPost(id){const {data,error}=await sb.from('poems').select('*').eq('id',id).single();if(error){msg(error.message,'error');return}$('postId').value=id;$('title').value=data.title||'';$('content').value=data.content||'';$('type').value=data.type||'puisi';$('theme').value=data.theme||'Catatan';$('image').value='';$('imageCaption').value=data.image_caption||'';showImagePreview(data.image_url||'');window.scrollTo({top:0,behavior:'smooth'});msg('Mode edit aktif.','ok')}
function resetPost(){$('postId').value='';$('postForm').reset();$('type').value='puisi';$('theme').value='Rindu';showImagePreview('');$('image').value='';$('imageCaption').value=''}
function showImagePreview(url){const box=$('imagePreview'),remove=$('removeImage');if(url){box.innerHTML='<img src=\"'+esc(url)+'\" alt=\"Pratinjau foto\">';remove.style.display='inline-block';}else{box.innerHTML='';remove.style.display='none';}}
async function uploadImage(file){if(!file)return null;if(!file.type.startsWith('image/'))throw new Error('File harus berupa gambar.');if(file.size>8*1024*1024)throw new Error('Ukuran foto maksimal 8 MB.');const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';const path=user.id+'/'+Date.now()+'-'+Math.random().toString(36).slice(2)+'.'+ext;const {error}=await sb.storage.from('poem-images').upload(path,file,{cacheControl:'3600',upsert:false});if(error)throw error;return sb.storage.from('poem-images').getPublicUrl(path).data.publicUrl}
async function savePost(status){const title=$('title').value.trim(),content=$('content').value.trim();if(!title||!content){msg('Judul dan isi wajib diisi.','error');return}msg('Menyimpan…');let imageUrl=null;try{const file=$('image').files[0];if(file)imageUrl=await uploadImage(file);}catch(e){msg('Foto gagal diunggah: '+e.message,'error');return}const existingId=$('postId').value;let existing=null;if(existingId){const r=await sb.from('poems').select('image_url').eq('id',existingId).single();existing=r.data||null}const payload={title,content,type:$('type').value,theme:$('theme').value,status,slug:slugify(title),updated_at:new Date().toISOString(),published_at:status==='published'?new Date().toISOString():null,image_url:imageUrl||existing?.image_url||null,image_caption:$('imageCaption').value.trim()||null};let res;if(existingId)res=await sb.from('poems').update(payload).eq('id',existingId);else{payload.author_id=user.id;payload.created_at=new Date().toISOString();res=await sb.from('poems').insert(payload)}if(res.error){msg('Gagal: '+res.error.message,'error');return}msg(status==='published'?'Berhasil diterbitkan.':'Draft tersimpan.','ok');resetPost();await loadPosts()}
async function togglePost(id,status){const next=status==='published'?'draft':'published';const {error}=await sb.from('poems').update({status:next,published_at:next==='published'?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',id);if(error){msg(error.message,'error');return}await loadPosts();msg(next==='published'?'Berhasil diterbitkan.':'Dipindahkan menjadi draft.','ok')}
async function deletePost(id){if(!confirm('Hapus tulisan ini?'))return;const {error}=await sb.from('poems').delete().eq('id',id);if(error){msg(error.message,'error');return}await loadPosts();msg('Tulisan dihapus.','ok')}
function renderSite(values){const wrap=$('contentEditor');wrap.innerHTML=groups.map(([name,prefix,keys])=>`<div class="site-group"><h3>${name}</h3><p>Semua teks di bagian ini bisa diedit dari sini.</p>${keys.map(k=>`<div class="site-field"><label>${esc(label(k))}<textarea data-site-key="${k}">${esc(values[k]??defaults[k]??'')}</textarea></label></div>`).join('')}</div>`).join('')}
async function loadSite(){const {data,error}=await sb.from('site_content').select('key,value');const values={...defaults};if(!error)(data||[]).forEach(x=>values[x.key]=x.value);else msg('site_content belum siap. Jalankan site-content.sql di Supabase lalu muat ulang.','error');renderSite(values)}
async function saveSite(){const fields=[...document.querySelectorAll('[data-site-key]')];msg('Menyimpan perubahan halaman…');const rows=fields.map(f=>({key:f.dataset.siteKey,value:f.value,updated_at:new Date().toISOString(),updated_by:user.id}));const {error}=await sb.from('site_content').upsert(rows,{onConflict:'key'});if(error){msg('Gagal menyimpan halaman: '+error.message,'error');return}msg('Semua perubahan halaman berhasil disimpan.','ok')}
async function resetSite(){if(!confirm('Kembalikan semua teks halaman ke versi awal?'))return;const rows=Object.entries(defaults).map(([key,value])=>({key,value,updated_at:new Date().toISOString(),updated_by:user.id}));const {error}=await sb.from('site_content').upsert(rows,{onConflict:'key'});if(error){msg(error.message,'error');return}renderSite(defaults);msg('Teks awal dikembalikan.','ok')}
$('image').addEventListener('change',e=>{const f=e.target.files[0];if(f)showImagePreview(URL.createObjectURL(f));});$('removeImage').onclick=()=>{ $('image').value=''; showImagePreview(''); };document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{$('image').addEventListener('change',e=>{const f=e.target.files[0];if(f)showImagePreview(URL.createObjectURL(f));});$('removeImage').onclick=()=>{ $('image').value=''; showImagePreview(''); };document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});$('newPost').onclick=resetPost;$('refreshPosts').onclick=loadPosts;$('saveDraft').onclick=()=>savePost('draft');$('publish').onclick=()=>savePost('published');$('saveSite').onclick=saveSite;$('resetContent').onclick=resetSite;$('logout').onclick=async()=>{await sb.auth.signOut();location.href='login.html'};init();
})();
