(function(){
const sb=supabase.createClient(window.SUPABASE_URL,window.SUPABASE_KEY);
const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
const slug=v=>String(v||"").toLowerCase().trim().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9\s-]/g,"").replace(/\s+/g,"-").replace(/-+/g,"-");
const fmt=v=>v?new Intl.DateTimeFormat("id-ID",{day:"2-digit",month:"long",year:"numeric"}).format(new Date(v)):"";
function n(r){let c=r.content||r.body||r.isi||r.poem||"";return{id:r.id,title:r.title||r.judul||"Tanpa judul",content:c,theme:r.theme||r.category||r.kategori||"Catatan",slug:r.slug||slug(r.title||r.judul),date:r.published_at||r.created_at,excerpt:r.excerpt||c.replace(/\s+/g," ").slice(0,190)+(c.length>190?"…":"")}}
async function run(){const {data,error}=await sb.from("poems").select("*").eq("status","published").order("published_at",{ascending:false,nullsFirst:false});if(error)throw error;const ps=(data||[]).map(n);render(ps);filters(ps)}
function link(p){return"puisi.html?slug="+encodeURIComponent(p.slug)}
function render(ps){const f=document.querySelector("[data-featured-poem]"),l=document.querySelector("[data-poem-list]");if(!ps.length){f.innerHTML="<p>Belum ada tulisan yang diterbitkan.</p>";return}let p=ps[0];f.innerHTML=`<div><div class="kicker">${esc(fmt(p.date))} · ${esc(p.theme)}</div><h3>${esc(p.title)}</h3><p class="excerpt">${esc(p.excerpt)}</p><a class="read" href="${link(p)}">baca selengkapnya →</a></div><aside class="feature-aside"><div class="small">TULISAN TERBARU</div><p class="vertical">${esc(p.content.slice(0,240))}${p.content.length>240?"…":""}</p></aside>`;l.innerHTML=ps.slice(1).map(p=>`<a class="row" href="${link(p)}"><span class="row-date">${esc(fmt(p.date))}</span><span class="row-title">${esc(p.title)}</span><span class="row-theme">${esc(p.theme)}</span><span class="arrow">→</span></a>`).join("")}
function filters(ps){const buttons=document.querySelectorAll("[data-poem-filter]"),l=document.querySelector("[data-poem-list]"),s=document.querySelector("[data-poem-search]");function draw(){let a=document.querySelector(".filters .active")?.dataset.poemFilter||"Semua",q=(s?.value||"").toLowerCase(),x=ps.filter(p=>(a==="Semua"||p.theme.toLowerCase()===a.toLowerCase())&&(!q||(p.title+" "+p.theme+" "+p.content).toLowerCase().includes(q)));l.innerHTML=x.map(p=>`<a class="row" href="${link(p)}"><span class="row-date">${esc(fmt(p.date))}</span><span class="row-title">${esc(p.title)}</span><span class="row-theme">${esc(p.theme)}</span><span class="arrow">→</span></a>`).join("")||"<p>Tidak ada tulisan yang cocok.</p>"}buttons.forEach(b=>b.onclick=()=>{buttons.forEach(x=>x.classList.remove("active"));b.classList.add("active");draw()});s?.addEventListener("input",draw)}
document.getElementById("themeToggle")?.addEventListener("click",()=>document.body.classList.toggle("dark"));
run().catch(e=>{console.error(e);document.querySelector("[data-featured-poem]").innerHTML="<p>Belum dapat memuat tulisan.</p>"});
})();